version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "postgres:16-alpine"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gin-project-example
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
